import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useTranslation from "next-translate/useTranslation";

import Main from "../components/Main";

const Home: NextPage = () => {
  const { t } = useTranslation("home");

  return (
    <div className={styles.container}>
      <Head>
        <title>Nehla 네일라</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1></h1>
        <Main />
      </main>

      {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
    </div>
  );
};

export default Home;
